"""
MCP Database Server with Factory Pattern.

This module provides database tools via MCP using the Factory Pattern
to support both PostgreSQL and SQLite databases transparently.
"""

import re
import sys
import logging
from pathlib import Path
from typing import Any, Optional

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Add parent directory to path so we can import adapters when running as script
_this_dir = Path(__file__).parent.resolve()
if str(_this_dir) not in sys.path:
    sys.path.insert(0, str(_this_dir))

from mcp.server.fastmcp import FastMCP

from adapters import DatabaseAdapter, DatabaseAdapterFactory

# Default limit for SELECT queries to prevent large result sets
DEFAULT_LIMIT = 1000

# Initialize FastMCP server
mcp = FastMCP("database")

# Primary adapter: user-connected PostgreSQL or explicitly-connected SQLite.
# Never overridden by system-level session file connections.
_primary_adapter: Optional[DatabaseAdapter] = None

# Session adapter: system-managed SQLite for uploaded session files.
# Set by connect_session_sqlite; does NOT override _primary_adapter.
_session_adapter: Optional[DatabaseAdapter] = None

# When set, list_tables (and schema discovery) will only surface these table names
# from the session adapter. Populated from the UI data-source selector so only
# the user's chosen files' tables are visible (not every table in the shared SQLite).
_session_allowed_tables: Optional[set] = None

# Store the latest reviewed CREATE TABLE proposal.
# create_table() will only execute when it matches this reviewed proposal
# and user_confirmed=True is explicitly provided.
_pending_create_table_review: Optional[dict[str, Any]] = None


def get_adapter() -> DatabaseAdapter:
    """Return primary adapter if available, else session adapter."""
    if _primary_adapter is not None:
        return _primary_adapter
    if _session_adapter is not None:
        return _session_adapter
    raise RuntimeError(
        "Database not connected. Please use 'connect_db' (PostgreSQL) or "
        "'connect_sqlite' (SQLite) tool first."
    )


async def _adapter_for_table(table_name: str) -> DatabaseAdapter:
    """Return the adapter that owns *table_name*.

    Heuristic: session-file tables are always named ``t_<...>`` (generated by
    the file ingestion service).  Everything else belongs to the primary DB.
    When only one adapter is connected, that adapter is always returned.
    """
    if _primary_adapter is not None and _session_adapter is not None:
        # Session tables are always prefixed with t_ by the file ingestion service.
        if str(table_name).startswith("t_"):
            return _session_adapter
        return _primary_adapter
    if _primary_adapter is not None:
        return _primary_adapter
    if _session_adapter is not None:
        return _session_adapter
    raise RuntimeError(
        "Database not connected. Please use 'connect_db' (PostgreSQL) or "
        "'connect_sqlite' (SQLite) tool first."
    )


def _split_column_defs(columns: str) -> list[str]:
    """Split SQL column definitions by top-level commas.

    Example: "a VARCHAR(10), b DECIMAL(10,2), c TEXT" ->
    ["a VARCHAR(10)", "b DECIMAL(10,2)", "c TEXT"]
    """
    items: list[str] = []
    current: list[str] = []
    depth = 0

    for ch in columns:
        if ch == "(":
            depth += 1
        elif ch == ")" and depth > 0:
            depth -= 1

        if ch == "," and depth == 0:
            part = "".join(current).strip()
            if part:
                items.append(part)
            current = []
            continue

        current.append(ch)

    last = "".join(current).strip()
    if last:
        items.append(last)

    return items


def _to_variable_type_rows(columns: str) -> list[tuple[str, str]]:
    """Parse column definition string into (variable, type) rows.

    The type may span multiple whitespace-separated tokens when an LLM emits
    something like ``DECIMAL(10, 2)`` (space after the inner comma). We walk
    forward from the second token, consuming tokens until paren depth returns
    to zero — that's where the type ends and constraints (NOT NULL, …) begin.
    Constraints are dropped from the displayed type so the review widget sees
    only the storage type the user needs to validate.
    """
    rows: list[tuple[str, str]] = []
    constraints = {"primary", "foreign", "unique", "check", "constraint"}

    for part in _split_column_defs(columns):
        tokens = part.split()
        if len(tokens) < 2:
            continue

        first = tokens[0].strip('"`').lower()
        if first in constraints:
            continue

        variable = tokens[0].strip('"`')

        type_tokens: list[str] = []
        depth = 0
        for tok in tokens[1:]:
            type_tokens.append(tok)
            depth += tok.count("(") - tok.count(")")
            if depth == 0:
                break
        if not type_tokens:
            continue
        dtype = " ".join(type_tokens)
        rows.append((variable, dtype))

    return rows



# =============================================================================
# Connection Management Tools
# =============================================================================


@mcp.tool()
async def connect_db(
    host: str,
    port: int,
    database: str,
    username: str,
    password: str
) -> str:
    """Connect to a PostgreSQL database. You must call this first before using any other database operations.

    Args:
        host: Database host (e.g., "localhost" or "127.0.0.1")
        port: Database port (default PostgreSQL port is 5432)
        database: Database name
        username: Database username
        password: Database password
    """
    global _primary_adapter

    if _primary_adapter is not None:
        await _primary_adapter.disconnect()

    _primary_adapter = DatabaseAdapterFactory.create_postgres()
    result = await _primary_adapter.connect(
        host=host,
        port=port,
        database=database,
        username=username,
        password=password
    )

    if "Failed" in result or "Error" in result:
        _primary_adapter = None

    return result


@mcp.tool()
async def connect_sqlite(file_path: str) -> str:
    """Connect to a SQLite database file (user-initiated). Creates the file if it doesn't exist.

    This sets the *primary* adapter and replaces any existing primary connection.
    Use ``connect_session_sqlite`` for system-managed session-file connections.

    Args:
        file_path: Path to the SQLite database file (e.g., "/path/to/db.sqlite" or "sqlite:///path/to/db.sqlite")
    """
    global _primary_adapter

    if _primary_adapter is not None:
        await _primary_adapter.disconnect()

    _primary_adapter = DatabaseAdapterFactory.create_sqlite()
    result = await _primary_adapter.connect(file_path=file_path)

    if "Failed" in result or "Error" in result:
        _primary_adapter = None

    return result


@mcp.tool()
async def connect_session_sqlite(file_path: str, allowed_tables: Optional[str] = None) -> str:
    """Connect a session-scoped SQLite file (uploaded by the user) WITHOUT overriding the primary DB.

    This sets only the *session* adapter so that the user's PostgreSQL connection
    (or any explicit primary connection) remains intact and can be queried alongside
    the session file.

    Args:
        file_path: Path to the SQLite database file for the uploaded session file.
        allowed_tables: Optional comma-separated list of table names to expose from this
            SQLite file. When set, ``list_tables`` will only surface these tables so the
            LLM sees exactly the tables from the files the user selected — not every table
            in the shared session SQLite (which may contain tables from other uploaded files).
    """
    global _session_adapter, _session_allowed_tables

    if _session_adapter is not None:
        await _session_adapter.disconnect()

    _session_adapter = DatabaseAdapterFactory.create_sqlite()
    result = await _session_adapter.connect(file_path=file_path)

    if "Failed" in result or "Error" in result:
        _session_adapter = None
        _session_allowed_tables = None
    else:
        if allowed_tables:
            _session_allowed_tables = {t.strip() for t in allowed_tables.split(",") if t.strip()}
        else:
            _session_allowed_tables = None

    return result


@mcp.tool()
async def disconnect_session_sqlite() -> str:
    """Disconnect the session-scoped SQLite adapter and clear the allowed-tables filter.

    Call this when the user switches away from a file (e.g. switches back to DB-only mode)
    so that subsequent ``list_tables`` / queries no longer surface tables from the old
    session file.
    """
    global _session_adapter, _session_allowed_tables

    if _session_adapter is None:
        _session_allowed_tables = None
        return "No session file adapter connected."

    try:
        await _session_adapter.disconnect()
    except Exception:
        pass
    finally:
        _session_adapter = None
        _session_allowed_tables = None

    return "Session file adapter disconnected."


@mcp.tool()
async def get_connection_info() -> str:
    """Get current database connection information (without showing password)."""
    parts: list[str] = []
    if _primary_adapter is not None:
        parts.append("Primary DB: " + await _primary_adapter.get_connection_info())
    if _session_adapter is not None:
        parts.append("Session file DB: " + await _session_adapter.get_connection_info())
    if not parts:
        return "Not connected to any database. Please use 'connect_db' or 'connect_sqlite' tool first."
    return "\n".join(parts)


@mcp.tool()
async def disconnect_database() -> str:
    """Disconnect from all active database connections (primary and session)."""
    global _primary_adapter, _session_adapter, _session_allowed_tables
    messages: list[str] = []
    if _primary_adapter is not None:
        messages.append(await _primary_adapter.disconnect())
        _primary_adapter = None
    if _session_adapter is not None:
        messages.append(await _session_adapter.disconnect())
        _session_adapter = None
    _session_allowed_tables = None
    return "\n".join(messages) if messages else "No active database connection."


# =============================================================================
# Schema Operations
# =============================================================================


def _filter_tables_result(tables_result: str, allowed: set) -> str:
    """Filter a 'Tables in database: a, b, c' string to only the names in *allowed*."""
    prefix = "Tables in database:"
    if prefix not in tables_result:
        # Unknown format — return as-is so we don't lose info.
        return tables_result
    idx = tables_result.index(prefix) + len(prefix)
    raw_names = [t.strip() for t in tables_result[idx:].split(",") if t.strip()]
    filtered = [t for t in raw_names if t in allowed]
    if not filtered:
        return f"{prefix} (none of the selected files have tables here)"
    return f"{prefix} {', '.join(filtered)}"


@mcp.tool()
async def list_tables() -> str:
    """List all tables across all connected databases.

    When both a primary database and a session file are connected, tables from
    each source are shown separately so the caller can distinguish them.
    """
    if _primary_adapter is None and _session_adapter is None:
        raise RuntimeError(
            "Database not connected. Please use 'connect_db' (PostgreSQL) or "
            "'connect_sqlite' (SQLite) tool first."
        )

    parts: list[str] = []

    if _primary_adapter is not None:
        primary_result = await _primary_adapter.list_tables()
        if _session_adapter is not None:
            parts.append(f"[Primary database]\n{primary_result}")
        else:
            parts.append(primary_result)

    if _session_adapter is not None:
        session_result = await _session_adapter.list_tables()
        # Filter to only the tables the user actually selected (if a restriction is set).
        if _session_allowed_tables:
            session_result = _filter_tables_result(session_result, _session_allowed_tables)
        if _primary_adapter is not None:
            parts.append(f"[Session file database]\n{session_result}")
        else:
            parts.append(session_result)

    return "\n\n".join(parts)


@mcp.tool()
async def describe_table(table_name: str) -> str:
    """Get structure of a table (columns, types, constraints).

    Automatically routes to the correct database (primary or session file)
    based on the table name.

    Args:
        table_name: Name of the table to describe
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.describe_table(table_name)


@mcp.tool()
async def get_schema() -> str:
    """Get the complete database schema (all tables, columns, constraints, etc.)."""
    if _primary_adapter is None and _session_adapter is None:
        raise RuntimeError("Database not connected.")
    parts: list[str] = []
    if _primary_adapter is not None:
        s = await _primary_adapter.get_schema()
        parts.append(f"[Primary database]\n{s}" if _session_adapter else s)
    if _session_adapter is not None:
        s = await _session_adapter.get_schema()
        parts.append(f"[Session file database]\n{s}" if _primary_adapter else s)
    return "\n\n".join(parts)


@mcp.tool()
async def get_table_stats(table_name: str) -> str:
    """Get statistics about a table (row count, size, etc.).

    Args:
        table_name: Name of the table
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.get_table_stats(table_name)


@mcp.tool()
async def show_create_table_schema(
    table_name: str,
    columns: str,
    primary_key: Optional[str] = None
) -> str:
    """Preview the CREATE TABLE schema and save it for user review before execution.

    Args:
        table_name: Name of the table to create
        columns: Column definitions in SQL format
        primary_key: Optional primary key column name (if not specified in columns)
    """
    global _pending_create_table_review

    # Just validate that some adapter is connected before storing the proposal.
    if _primary_adapter is None and _session_adapter is None:
        return "Error: No database connected. Please connect first."

    rows = _to_variable_type_rows(columns)

    _pending_create_table_review = {
        "table_name": table_name,
        "columns": columns,
        "primary_key": primary_key,
    }

    if not rows:
        return (
            "[CREATE_TABLE_SCHEMA_PREVIEW]\n"
            f"Proposed table: `{table_name}`\n"
            "Cannot parse the column list from input `columns`. "
            "Please enter the columns in the following format: `col_name TYPE, col2 TYPE, ...`"
        )

    table_md = ["| Variable | Type |", "|---|---|"]
    for variable, dtype in rows:
        table_md.append(f"| `{variable}` | `{dtype}` |")

    pk_text = primary_key if primary_key else "(none)"

    import json
    payload = {
        "table_name": table_name,
        "primary_key": primary_key,
        "columns": [{"variable": variable, "type": dtype} for variable, dtype in rows],
    }
    payload_json = json.dumps(payload, ensure_ascii=False)

    return (
        "[CREATE_TABLE_SCHEMA_PREVIEW]\n"
        f"Proposed table: `{table_name}`\n"
        f"Primary key: `{pk_text}`\n\n"
        "Please review the schema as follows:\n\n"
        + "\n".join(table_md)
        + "\n\nConfirm the schema is correct.\n\n"
        + "[CREATE_TABLE_SCHEMA_JSON_START]\n"
        + payload_json
        + "\n[CREATE_TABLE_SCHEMA_JSON_END]"
    )


# =============================================================================
# DDL Operations (Create, Alter Tables)
# =============================================================================


@mcp.tool()
async def create_table(
    table_name: str,
    columns: str,
    primary_key: Optional[str] = None,
    user_confirmed: bool = False
) -> str:
    """Create a new table in the database after schema review confirmation.
    
    Args:
        table_name: Name of the table to create
        columns: Column definitions in SQL format (e.g., "id INTEGER PRIMARY KEY, name TEXT, email TEXT")
        primary_key: Optional primary key column name (if not specified in columns)
        user_confirmed: Must be True only after user has validated the schema preview
    """
    global _pending_create_table_review

    if not user_confirmed:
        return (
            "Blocked: create_table requires explicit confirmation. "
            "Please call `show_create_table_schema` first, let user validate all column types, "
            "then call `create_table` with `user_confirmed=True`."
        )

    if not _pending_create_table_review:
        return (
            "Blocked: no reviewed schema found. "
            "Call `show_create_table_schema` first and get user confirmation before creating table."
        )

    expected = _pending_create_table_review
    if (
        expected.get("table_name") != table_name
        or expected.get("columns") != columns
        or expected.get("primary_key") != primary_key
    ):
        return (
            "Blocked: schema mismatch with the reviewed proposal. "
            "Please run `show_create_table_schema` again with the exact schema to be created, "
            "then ask for confirmation."
        )

    adapter = await _adapter_for_table(table_name)
    result = await adapter.create_table(table_name, columns, primary_key)

    if "Error" not in result and "Failed" not in result:
        _pending_create_table_review = None

    return result


@mcp.tool()
async def alter_table(
    action: str,
    table_name: str,
    column_name: str,
    column_def: Optional[str] = None,
    new_column_name: Optional[str] = None
) -> str:
    """Alter a table structure (add, drop, modify, rename columns).
    
    Args:
        action: Action to perform - "add_column", "drop_column", "modify_column", "rename_column"
        table_name: Name of the table to alter
        column_name: Name of the column (for add/modify/drop/rename)
        column_def: Column definition (required for "add_column" and "modify_column")
                   Examples:
                   - "VARCHAR(100)" for add_column
                   - "VARCHAR(200)" or "SET NOT NULL" for modify_column
        new_column_name: New name for the column (required for "rename_column")
    
    Examples:
        - Add column: action="add_column", column_name="email", column_def="VARCHAR(255)"
        - Drop column: action="drop_column", column_name="old_column"
        - Modify column: action="modify_column", column_name="name", column_def="VARCHAR(200)"
        - Rename column: action="rename_column", column_name="old_name", new_column_name="new_name"
    
    Note: SQLite has limited ALTER TABLE support (no modify_column).
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.alter_table(action, table_name, column_name, column_def, new_column_name)


@mcp.tool()
async def create_db_from_spec(spec_text: str) -> str:
    """Create database schema from a specification text (SQL DDL statements).

    Args:
        spec_text: SQL DDL statements to create tables, constraints, etc.
    """
    # DDL goes to the primary DB (never session SQLite).
    adapter = _primary_adapter if _primary_adapter is not None else get_adapter()
    return await adapter.create_from_spec(spec_text)


# =============================================================================
# DML Operations (Insert, Select, Update, Delete)
# =============================================================================


@mcp.tool()
async def insert_data(
    table_name: str,
    data: dict[str, Any]
) -> str:
    """Insert data into a table.

    Args:
        table_name: Name of the table
        data: Dictionary with column names as keys and values to insert.
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.insert_data(table_name, data)


@mcp.tool()
async def select_data(
    table_name: str,
    columns: str = "*",
    where_clause: Optional[str] = None,
    limit: int = DEFAULT_LIMIT,
    order_by: Optional[str] = None
) -> str:
    """Select data from a table.

    Automatically routes to the correct database (primary or session file)
    based on the table name.

    Args:
        table_name: Name of the table
        columns: Column names to select (default: "*")
        where_clause: Optional WHERE clause (e.g., "age > 18")
        limit: Number of rows to return (default: 1000)
        order_by: Optional ORDER BY clause (e.g., "name ASC")
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.select_data(table_name, columns, where_clause, limit, order_by)


@mcp.tool()
async def update_data(
    table_name: str,
    data: dict[str, Any],
    where_clause: str
) -> str:
    """Update data in a table.

    Args:
        table_name: Name of the table
        data: Dictionary with column names and new values.
        where_clause: WHERE clause to identify rows to update (e.g., "id = 1")
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.update_data(table_name, data, where_clause)


@mcp.tool()
async def delete_data(
    table_name: str,
    where_clause: str
) -> str:
    """Delete data from a table.

    Args:
        table_name: Name of the table
        where_clause: WHERE clause to identify rows to delete (e.g., "id = 1")
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.delete_data(table_name, where_clause)


@mcp.tool()
async def preview_table(table_name: str, limit: int = 10) -> str:
    """Preview a table with a limited number of rows.

    Args:
        table_name: Name of the table
        limit: Number of rows to preview (default: 10)
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.preview_table(table_name, limit)


# =============================================================================
# Query Execution
# =============================================================================


def _add_limit(query: str) -> str:
    """Auto-add LIMIT to SELECT queries if not present."""
    query = query.strip()
    # Normalize trailing semicolon so appending LIMIT stays valid SQL.
    base_query = query[:-1].strip() if query.endswith(";") else query
    query_upper = base_query.upper()

    # Only add limit to SELECT queries
    if not query_upper.startswith("SELECT"):
        return query

    # Skip if already has LIMIT
    if "LIMIT" in query_upper:
        return query

    # Add LIMIT
    return f"{base_query} LIMIT {DEFAULT_LIMIT}"


def _first_table_name_from_sql(query: str) -> Optional[str]:
    """Best-effort extraction of the first table name referenced in a SQL query.

    Handles the most common patterns:
      SELECT ... FROM <table>
      INSERT INTO <table>
      UPDATE <table>
      DELETE FROM <table>
    Returns None if no match is found.
    """
    patterns = (
        r"\bFROM\s+([`\"\[]?[\w.]+[`\"\]]?)",
        r"\bJOIN\s+([`\"\[]?[\w.]+[`\"\]]?)",
        r"\bINTO\s+([`\"\[]?[\w.]+[`\"\]]?)",
        r"\bUPDATE\s+([`\"\[]?[\w.]+[`\"\]]?)",
    )
    upper = query.upper()
    for pattern in patterns:
        m = re.search(pattern, upper)
        if m:
            # Return the original-case token from the same position.
            start = m.start(1)
            end = m.end(1)
            raw = query[start:end].strip("`\"[]")
            # Strip schema prefix (e.g. "public.users" → "users")
            return raw.split(".")[-1]
    return None


@mcp.tool()
async def execute_query(query: str) -> str:
    """Execute a custom SQL query.

    Automatically routes to the correct database (primary or session file)
    based on the first table name referenced in the query.

    Args:
        query: SQL query to execute
    """
    query = _add_limit(query)

    # When both adapters exist, route based on the first table in the SQL.
    if _primary_adapter is not None and _session_adapter is not None:
        table_name = _first_table_name_from_sql(query)
        adapter = await _adapter_for_table(table_name or "")
    else:
        adapter = get_adapter()

    return await adapter.execute_query(query)


@mcp.tool()
async def export_table_to_excel(
    table_name: str,
    columns: str = "*",
    where_clause: str | None = None,
    limit: int | None = None,
    offset: int | None = None,
) -> dict:
    """Export table data to Excel file. Returns dict with base64 content and filename.

    Streams rows from the DB in chunks via ``adapter.stream_query`` and writes
    them through xlsxwriter's ``constant_memory`` mode to a temp .xlsx on
    disk — each row is flushed as the next one is written, so the full
    result set is never materialized in RAM.

    Args:
        table_name: Name of the table to export
        columns: Column names to export (default: "*")
        where_clause: Optional WHERE clause to filter data (without the WHERE keyword)
        limit: Optional SQLite LIMIT (row cap)
        offset: Optional SQLite OFFSET (skip rows; use with limit for slices e.g. rows 10–20 → limit 11, offset 9)
    """
    import base64
    import logging
    import os
    import tempfile
    from datetime import date, datetime
    from decimal import Decimal
    from uuid import UUID

    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)

    try:
        import xlsxwriter
    except ImportError:
        return {
            "error": (
                "xlsxwriter is required for Excel export. From repo root: "
                "`cd database && uv sync`, then restart the API server."
            )
        }

    def _xlsx_safe(v):
        # xlsxwriter accepts None/bool/int/float/str/datetime/date natively.
        # Coerce other DB types so write_row doesn't fall back to slow conversion.
        if v is None or isinstance(v, (bool, int, float, str, datetime, date)):
            return v
        if isinstance(v, Decimal):
            return float(v)
        if isinstance(v, UUID):
            return str(v)
        if isinstance(v, (bytes, bytearray)):
            return v.hex()
        return str(v)

    # Build query
    query = f"SELECT {columns} FROM {table_name}"
    if where_clause:
        query += f" WHERE {where_clause}"
    if limit is not None:
        lim = int(limit)
        if lim < 0:
            return {"error": "limit must be non-negative"}
        query += f" LIMIT {lim}"
    elif offset is not None:
        # SQLite requires LIMIT when using OFFSET; -1 means no upper bound.
        query += " LIMIT -1"
    if offset is not None:
        off = int(offset)
        if off < 0:
            return {"error": "offset must be non-negative"}
        query += f" OFFSET {off}"

    logger.info(f"[export_table_to_excel] table={table_name}, query={query}")

    adapter = await _adapter_for_table(table_name)

    tmp = tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False)
    tmp_path = tmp.name
    tmp.close()

    try:
        # constant_memory=True: each row is flushed as the next is written; can't
        #   seek back to modify earlier cells.
        # strings_to_urls=False: skip the regex that turns "http://..." strings
        #   into hyperlinks — significantly faster on text-heavy exports.
        wb = xlsxwriter.Workbook(
            tmp_path,
            {
                "constant_memory": True,
                "strings_to_urls": False,
                "default_date_format": "yyyy-mm-dd hh:mm:ss",
            },
        )
        col_names: list[str] | None = None
        row_count = 0
        try:
            ws = wb.add_worksheet()
            row_idx = 0
            try:
                async for cols, rows in adapter.stream_query(query, chunk_size=5000):
                    if col_names is None:
                        col_names = list(cols)
                        ws.write_row(0, 0, col_names)
                        row_idx = 1
                    for row in rows:
                        ws.write_row(row_idx, 0, [_xlsx_safe(row[c]) for c in col_names])
                        row_idx += 1
                    row_count += len(rows)
            except Exception as e:
                logger.error(f"[export_table_to_excel] query stream error: {e}")
                return {"error": str(e)}
        finally:
            wb.close()

        if col_names is None:
            return {"error": "No data found"}

        file_size = os.path.getsize(tmp_path)

        # Stream the xlsx file through base64 so we don't hold both the raw
        # bytes and the encoded string in RAM at once. Reads in multiples of 3
        # so each chunk encodes without intermediate padding.
        b64_buf = bytearray()
        with open(tmp_path, "rb") as f:
            while True:
                chunk = f.read(3 * 64 * 1024)
                if not chunk:
                    break
                b64_buf += base64.b64encode(chunk)
        b64 = b64_buf.decode("ascii")
        del b64_buf

        filename = f"{table_name}.xlsx"
        logger.info(
            f"[export_table_to_excel] success: {row_count} rows, "
            f"file={file_size} bytes, base64 length: {len(b64)}"
        )
        return {"base64": b64, "filename": filename, "row_count": row_count}
    except Exception as e:
        logger.exception("[export_table_to_excel] ERROR")
        return {"error": str(e)}
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


@mcp.tool()
async def run_mutation(sql: str) -> str:
    """Run a mutation query (INSERT, UPDATE, DELETE) and return affected rows.

    Args:
        sql: SQL mutation query (INSERT, UPDATE, or DELETE)
    """
    if _primary_adapter is not None and _session_adapter is not None:
        table_name = _first_table_name_from_sql(sql)
        adapter = await _adapter_for_table(table_name or "")
    else:
        adapter = get_adapter()
    return await adapter.run_mutation(sql)


@mcp.tool()
async def validate_sql(sql: str) -> str:
    """Validate DDL (CREATE/ALTER/DROP/TRUNCATE) via dry-run + rollback.

    For SELECT/INSERT/UPDATE/DELETE use ``explain_sql`` instead.

    Args:
        sql: DDL statement to validate
    """
    if _primary_adapter is not None and _session_adapter is not None:
        table_name = _first_table_name_from_sql(sql)
        adapter = await _adapter_for_table(table_name or "")
    else:
        adapter = get_adapter()
    return await adapter.validate_sql(sql)


@mcp.tool()
async def explain_sql(sql: str) -> str:
    """Explain the execution plan of a SQL query.

    Args:
        sql: SQL query to explain
    """
    if _primary_adapter is not None and _session_adapter is not None:
        table_name = _first_table_name_from_sql(sql)
        adapter = await _adapter_for_table(table_name or "")
    else:
        adapter = get_adapter()
    return await adapter.explain_sql(sql)


# =============================================================================
# Additional Operations
# =============================================================================


@mcp.tool()
async def list_databases() -> str:
    """List all databases (PostgreSQL) or show current database (SQLite)."""
    adapter = get_adapter()
    return await adapter.list_databases()


@mcp.tool()
async def generate_schema_doc(format: str = "text") -> str:
    """Generate documentation for the database schema.

    Args:
        format: Output format - "text" or "markdown"
    """
    adapter = get_adapter()
    return await adapter.generate_schema_doc(format)


@mcp.tool()
async def manage_constraint(
    action: str,
    table_name: str,
    constraint_name: str,
    constraint_def: Optional[str] = None
) -> str:
    """Manage constraints (add, drop) on a table.

    Args:
        action: "add" or "drop"
        table_name: Name of the table
        constraint_name: Name of the constraint
        constraint_def: Constraint definition (required for "add", e.g., "CHECK (age > 0)")
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.manage_constraint(action, table_name, constraint_name, constraint_def)


@mcp.tool()
async def manage_trigger(
    action: str,
    trigger_name: str,
    table_name: str,
    trigger_def: Optional[str] = None
) -> str:
    """Manage triggers (create, drop) on a table.

    Args:
        action: "create" or "drop"
        trigger_name: Name of the trigger
        table_name: Name of the table
        trigger_def: Trigger definition (required for "create")
    """
    adapter = await _adapter_for_table(table_name)
    return await adapter.manage_trigger(action, trigger_name, table_name, trigger_def)


# =============================================================================
# Excel/CSV Import Tools
# =============================================================================

try:
    import pandas as pd
    PANDAS_AVAILABLE = True
except ImportError:
    PANDAS_AVAILABLE = False


@mcp.tool()
async def import_excel_to_db(
    file_path: str,
    table_name: str,
    column_mapping: Optional[str] = None,
    if_exists: str = "append"
) -> str:
    """Import data from Excel file directly into database table.

    Args:
        file_path: Path to Excel file (.xlsx or .xls)
        table_name: Target database table name
        column_mapping: Optional mapping like "excel_col1:db_col1,excel_col2:db_col2"
        if_exists: What to do if table exists - "append", "fail", "replace" (default: "append")
    """
    if not PANDAS_AVAILABLE:
        return "Error: pandas is required. Please install: pip install pandas openpyxl"

    from pathlib import Path

    try:
        file = Path(file_path)
        if not file.exists():
            return f"Error: File not found at '{file_path}'"

        # Read Excel
        df = pd.read_excel(file_path)

        # Apply column mapping if provided
        if column_mapping:
            mappings = {}
            for pair in column_mapping.split(","):
                if ":" in pair:
                    exc, dbc = pair.split(":")
                    mappings[exc.strip()] = dbc.strip()
            df = df.rename(columns=mappings)

        columns = df.columns.tolist()
        records = df.to_dict(orient="records")

        # Get adapter and insert
        adapter = await _adapter_for_table(table_name)

        # Insert in batches
        batch_size = 100
        inserted = 0
        for i in range(0, len(records), batch_size):
            batch = records[i:i+batch_size]
            for record in batch:
                try:
                    await adapter.insert_data(table_name, record)
                    inserted += 1
                except Exception as e:
                    return f"Error inserting row {i}: {str(e)}"

        return f"Successfully imported {inserted} rows from '{file_path}' into table '{table_name}'. Columns: {columns}"
    except Exception as e:
        return f"Error importing Excel to database: {str(e)}"


@mcp.tool()
async def import_csv_to_db(
    file_path: str,
    table_name: str,
    column_mapping: Optional[str] = None,
    if_exists: str = "append",
    delimiter: str = ","
) -> str:
    """Import data from CSV file directly into database table.

    Args:
        file_path: Path to CSV file
        table_name: Target database table name
        column_mapping: Optional mapping like "csv_col1:db_col1,csv_col2:db_col2"
        if_exists: What to do if table exists - "append", "fail", "replace" (default: "append")
        delimiter: CSV delimiter (default: ",")
    """
    try:
        from pathlib import Path

        file = Path(file_path)
        if not file.exists():
            return f"Error: File not found at '{file_path}'"

        # Read CSV
        df = pd.read_csv(file_path, delimiter=delimiter)

        # Apply column mapping if provided
        if column_mapping:
            mappings = {}
            for pair in column_mapping.split(","):
                if ":" in pair:
                    exc, dbc = pair.split(":")
                    mappings[exc.strip()] = dbc.strip()
            df = df.rename(columns=mappings)

        columns = df.columns.tolist()
        records = df.to_dict(orient="records")

        # Get adapter and insert
        adapter = await _adapter_for_table(table_name)

        # Insert in batches
        batch_size = 100
        inserted = 0
        for i in range(0, len(records), batch_size):
            batch = records[i:i+batch_size]
            for record in batch:
                try:
                    await adapter.insert_data(table_name, record)
                    inserted += 1
                except Exception as e:
                    return f"Error inserting row {i}: {str(e)}"

        return f"Successfully imported {inserted} rows from '{file_path}' into table '{table_name}'. Columns: {columns}"
    except ImportError:
        return "Error: pandas is required. Please install: pip install pandas"
    except Exception as e:
        return f"Error importing CSV to database: {str(e)}"


# =============================================================================
# Main Entry Point
# =============================================================================


def main():
    """Initialize and run the MCP server."""
    mcp.run(transport='stdio')


if __name__ == "__main__":
    main()
